### ISSUE TITLE
Security issue.

### ISSUE THREAD

**Issue by indyaah** [duncwinn/twicf-signup#3]
As usual going through code (part of learning process) ended up looking into txt.txt which contains db connection string with credentials in it IN PLAIN STRING!!

You might want to look into that.

**Comment by duncwinn** [comment]
Thanks, are you talking about password=JGq4DVRwcZzU-hq10n4U_JeSv4aEG9SQ

The beauty of Spring of spring security is that it will generate a temporary password in dev mode if you don't assign on. txt.txt was a dump during dev (left in error) but all passwords are temporary (I believe).

If I'm missing something please let me know.

**Comment by indyaah** [comment]
![screenshot from 2015-01-12 00 03 43](https://cloud.githubusercontent.com/assets/1032931/5696267/d527b0ca-99ee-11e4-8f0e-bb03ded3f362.png)
I understand that part but the credentials still work. 

PS : Tried to smudge as much possible to show that the credentials still work.

**Comment by duncwinn** [comment]
oh wow - ok thanks I'll take a look

**Comment by duncwinn** [comment]
Ok, I think what happened is that I took a dump of the startup to do some debugging and the db connection string was written out - nothing to do with spring security. 

I'm not a dba so I just blew away the db and provisioned a new one and re entered the data.

Thanks for the heads up. I think it should all be sorted now. If not please let me know else I'll close the issue.
